/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * The duration for which access is granted
 */
export type AcceptConsentDtoDuration = typeof AcceptConsentDtoDuration[keyof typeof AcceptConsentDtoDuration];


export const AcceptConsentDtoDuration = {
  '30m': '30m',
  '1h': '1h',
  '2h': '2h',
  '4h': '4h',
  '24h': '24h',
} as const;
