/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import type { AppointmentResponseDtoStatus } from './appointmentResponseDtoStatus';

export interface AppointmentResponseDto {
  id: string;
  appointmentNo: string;
  appointmentType: string;
  doctorName: string;
  /** ISO date string YYYY-MM-DD */
  date: string;
  hospitalLocation: string;
  status: AppointmentResponseDtoStatus;
  address: string;
  phone: string;
  email: string;
}
