/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */

export type AppointmentResponseDtoStatus = typeof AppointmentResponseDtoStatus[keyof typeof AppointmentResponseDtoStatus];


export const AppointmentResponseDtoStatus = {
  accepted: 'accepted',
  cancelled: 'cancelled',
  pending: 'pending',
} as const;
