/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * Message indicating the status of the blockchain gateway
 */
export type BlockchainHealthResponseDtoMessage = typeof BlockchainHealthResponseDtoMessage[keyof typeof BlockchainHealthResponseDtoMessage];


export const BlockchainHealthResponseDtoMessage = {
  up: 'up',
  down: 'down',
} as const;
