/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import type { BlockchainHealthResponseDtoMessage } from './blockchainHealthResponseDtoMessage';

export interface BlockchainHealthResponseDto {
  /** Message indicating the status of the blockchain gateway */
  message: BlockchainHealthResponseDtoMessage;
}
