/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */

export interface DownloadUrlResponseDto {
  /** Presigned URL that grants temporary download access to the encrypted file */
  url: string;
  /** S3 object key for the requested file */
  objectKey: string;
  /** Number of seconds until the presigned URL expires */
  expiresInSeconds: number;
  /** Direct backend URL to download the decrypted file */
  downloadUrl: string;
}
