/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */

export type GetHistorySort = typeof GetHistorySort[keyof typeof GetHistorySort];


export const GetHistorySort = {
  asc: 'asc',
  desc: 'desc',
} as const;
