/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import type { DatabaseHealth } from './databaseHealth';
import type { HealthResponseStatus } from './healthResponseStatus';

export interface HealthResponse {
  status: HealthResponseStatus;
  /** Application uptime in seconds */
  uptime: number;
  /** ISO timestamp of the health check */
  timestamp: string;
  message: string;
  database?: DatabaseHealth;
}
