/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import type { HistoryEventDtoAdditionalData } from './historyEventDtoAdditionalData';

export interface HistoryEventDto {
  id: string;
  /** Originating source: local | blockchain */
  source: string;
  /** Event type / action performed */
  eventType: string;
  /** UUID of the actor */
  actorId?: string;
  /** UUID of the target resource */
  targetResource?: string;
  /** Original filename of the document */
  fileName?: string;
  /** Document category */
  category?: string;
  /** When the event occurred */
  timestamp: string;
  /** Human-readable summary */
  description?: string;
  /** Extra metadata */
  additionalData?: HistoryEventDtoAdditionalData;
}
