/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * Extra metadata
 */
export type HistoryEventDtoAdditionalData = { [key: string]: unknown };
