/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */

export * from './acceptConsentDto';
export * from './acceptConsentDtoDuration';
export * from './appointmentResponseDto';
export * from './appointmentResponseDtoStatus';
export * from './appointmentsControllerFindAllByAuthUserId200';
export * from './appointmentsControllerFindAllByAuthUserIdParams';
export * from './appointmentsControllerFindOneByIdParams';
export * from './authMessageDto';
export * from './blockchainHealthResponseDto';
export * from './blockchainHealthResponseDtoStatus';
export * from './createAppointmentDto';
export * from './createMedicalRecordRequestDto';
export * from './createMedicalRecordResponseDto';
export * from './databaseHealth';
export * from './databaseHealthStatus';
export * from './deleteAppointmentDto';
export * from './deleteMedicalRecordResponseDto';
export * from './downloadUrlResponseDto';
export * from './editAppointmentDto';
export * from './errorResponseDto';
export * from './getHistoryParams';
export * from './getHistorySort';
export * from './healthResponseDto';
export * from './healthResponseDtoStatus';
export * from './historyEventDto';
export * from './historyEventDtoAdditionalData';
export * from './loginDto';
export * from './medicalHistoryResponseDto';
export * from './medicalRecordItemResponseDto';
export * from './medicalRecordItemResponseDtoRequestStatus';
export * from './medicalRecordListResponseDto';
export * from './networkStatusDto';
export * from './networkStatusDtoStatus';
export * from './registerDto';
export * from './s3VaultControllerUploadFileBody';
export * from './s3VaultControllerUploadFileBodyCategory';
export * from './subStatusDto';
export * from './subStatusDtoStatus';
export * from './updateMedicalRecordRequestDto';
export * from './updateMedicalRecordRequestDtoCategory';