/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import type { S3VaultControllerUploadFileBodyCategory } from './s3VaultControllerUploadFileBodyCategory';

export type S3VaultControllerUploadFileBody = {
  /** Medical record file to encrypt and upload */
  file: Blob;
  /** UUID of the patient this record belongs to */
  patientId: string;
  /** Category of the medical record */
  category?: S3VaultControllerUploadFileBodyCategory;
  /** Optional notes about the record */
  notes?: string;
  /** Name of the doctor who issued the record */
  doctorName?: string;
  /** Name of the hospital/clinic */
  hospitalName?: string;
  /** Date when the record was issued */
  recordDate?: string;
};
