/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * Category of the medical record
 */
export type S3VaultControllerUploadFileBodyCategory = typeof S3VaultControllerUploadFileBodyCategory[keyof typeof S3VaultControllerUploadFileBodyCategory];


export const S3VaultControllerUploadFileBodyCategory = {
  lab_report: 'lab_report',
  prescription: 'prescription',
  imaging: 'imaging',
  discharge_summary: 'discharge_summary',
  vaccination: 'vaccination',
  other: 'other',
} as const;
