/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */

export type UpdateMedicalRecordRequestDtoCategory = typeof UpdateMedicalRecordRequestDtoCategory[keyof typeof UpdateMedicalRecordRequestDtoCategory];


export const UpdateMedicalRecordRequestDtoCategory = {
  lab_report: 'lab_report',
  prescription: 'prescription',
  imaging: 'imaging',
  discharge_summary: 'discharge_summary',
  vaccination: 'vaccination',
  other: 'other',
} as const;
