OrdererOrgs:
  - Name: Orderer
    Domain: trustmed.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Hospital
    Domain: hospital.trustmed.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Insurance
    Domain: insurance.trustmed.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
