version: '3.7'

networks:
  trustmed:
    name: trustmed-network

services:
  # 1. The Orderer
  orderer.trustmed.com:
    container_name: orderer.trustmed.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/trustmed.com/orderers/orderer.trustmed.com/msp:/var/hyperledger/orderer/msp
    ports:
      - 7050:7050
    networks:
      - trustmed

  # 2. Hospital Peer
  peer0.hospital.trustmed.com:
    container_name: peer0.hospital.trustmed.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trustmed-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.hospital.trustmed.com
      - CORE_PEER_ADDRESS=peer0.hospital.trustmed.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hospital.trustmed.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/hospital.trustmed.com/peers/peer0.hospital.trustmed.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 7051:7051
    networks:
      - trustmed

  # 3. Insurance Peer
  peer0.insurance.trustmed.com:
    container_name: peer0.insurance.trustmed.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trustmed-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.insurance.trustmed.com
      - CORE_PEER_ADDRESS=peer0.insurance.trustmed.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.insurance.trustmed.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/insurance.trustmed.com/peers/peer0.insurance.trustmed.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 9051:9051
    networks:
      - trustmed

  # 4. Fabric CLI (The Control Center)
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.hospital.trustmed.com:7051
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.trustmed.com/users/Admin@hospital.trustmed.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./:/opt/gopath/src/github.com/hyperledger/fabric/peer/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
      - trustmed
    depends_on:
      - orderer.trustmed.com
      - peer0.hospital.trustmed.com
      - peer0.insurance.trustmed.com
