import type { Appointment } from "./types";

export const SEED_APPOINTMENTS: Appointment[] = [
    {
        id: "1",
        appointmentNo: "D001",
        appointmentType: "Psychiatric",
        doctorName: "Dr. S. Sumanaweera",
        date: "2025-04-12",
        hospitalLocation: "Maharagama",
        status: "accepted",
        address: "42 Flower Road, Colombo",
        phone: "+94771234567",
        email: "kate@example.com",
    },
    {
        id: "2",
        appointmentNo: "D002",
        appointmentType: "Dermatology",
        doctorName: "Dr. P. Perera",
        date: "2025-04-15",
        hospitalLocation: "Colombo",
        status: "pending",
        address: "12 Lake View, Nugegoda",
        phone: "+94772345678",
        email: "kate@example.com",
    },
    {
        id: "3",
        appointmentNo: "D003",
        appointmentType: "Cardiology",
        doctorName: "Dr. A. Fernando",
        date: "2025-04-18",
        hospitalLocation: "Kandy",
        status: "cancelled",
        address: "8 Hill Street, Kandy",
        phone: "+94773456789",
        email: "kate@example.com",
    },
    {
        id: "4",
        appointmentNo: "D004",
        appointmentType: "General",
        doctorName: "Dr. R. Silva",
        date: "2025-04-22",
        hospitalLocation: "Maharagama",
        status: "accepted",
        address: "42 Flower Road, Colombo",
        phone: "+94771234567",
        email: "kate@example.com",
    },
    {
        id: "5",
        appointmentNo: "D005",
        appointmentType: "Orthopedics",
        doctorName: "Dr. M. Jayasinghe",
        date: "2025-04-25",
        hospitalLocation: "Galle",
        status: "pending",
        address: "3 Fort Lane, Galle",
        phone: "+94774567890",
        email: "kate@example.com",
    },
    {
        id: "6",
        appointmentNo: "D006",
        appointmentType: "Pediatrics",
        doctorName: "Dr. N. Wickramasinghe",
        date: "2025-04-28",
        hospitalLocation: "Colombo",
        status: "accepted",
        address: "42 Flower Road, Colombo",
        phone: "+94771234567",
        email: "kate@example.com",
    },
    {
        id: "7",
        appointmentNo: "D007",
        appointmentType: "ENT",
        doctorName: "Dr. K. Ratnayake",
        date: "2025-05-02",
        hospitalLocation: "Negombo",
        status: "pending",
        address: "15 Beach Road, Negombo",
        phone: "+94775678901",
        email: "kate@example.com",
    },
    {
        id: "8",
        appointmentNo: "D008",
        appointmentType: "Neurology",
        doctorName: "Dr. L. De Silva",
        date: "2025-05-06",
        hospitalLocation: "Colombo",
        status: "accepted",
        address: "42 Flower Road, Colombo",
        phone: "+94771234567",
        email: "kate@example.com",
    },
    {
        id: "9",
        appointmentNo: "D009",
        appointmentType: "Ophthalmology",
        doctorName: "Dr. T. Mendis",
        date: "2025-05-10",
        hospitalLocation: "Maharagama",
        status: "cancelled",
        address: "9 Temple Road, Maharagama",
        phone: "+94776789012",
        email: "kate@example.com",
    },
    {
        id: "10",
        appointmentNo: "D010",
        appointmentType: "Dermatology",
        doctorName: "Dr. P. Perera",
        date: "2025-05-14",
        hospitalLocation: "Colombo",
        status: "pending",
        address: "12 Lake View, Nugegoda",
        phone: "+94772345678",
        email: "kate@example.com",
    },
    {
        id: "11",
        appointmentNo: "D011",
        appointmentType: "Psychiatric",
        doctorName: "Dr. S. Sumanaweera",
        date: "2025-05-18",
        hospitalLocation: "Maharagama",
        status: "accepted",
        address: "42 Flower Road, Colombo",
        phone: "+94771234567",
        email: "kate@example.com",
    },
    {
        id: "12",
        appointmentNo: "D012",
        appointmentType: "General",
        doctorName: "Dr. R. Silva",
        date: "2025-05-22",
        hospitalLocation: "Kandy",
        status: "pending",
        address: "8 Hill Street, Kandy",
        phone: "+94773456789",
        email: "kate@example.com",
    },
    {
        id: "13",
        appointmentNo: "D013",
        appointmentType: "Cardiology",
        doctorName: "Dr. A. Fernando",
        date: "2025-05-26",
        hospitalLocation: "Galle",
        status: "accepted",
        address: "3 Fort Lane, Galle",
        phone: "+94774567890",
        email: "kate@example.com",
    },
    {
        id: "14",
        appointmentNo: "D014",
        appointmentType: "Orthopedics",
        doctorName: "Dr. M. Jayasinghe",
        date: "2025-05-30",
        hospitalLocation: "Colombo",
        status: "cancelled",
        address: "42 Flower Road, Colombo",
        phone: "+94771234567",
        email: "kate@example.com",
    },
    {
        id: "15",
        appointmentNo: "D015",
        appointmentType: "Pediatrics",
        doctorName: "Dr. N. Wickramasinghe",
        date: "2025-06-03",
        hospitalLocation: "Negombo",
        status: "pending",
        address: "15 Beach Road, Negombo",
        phone: "+94775678901",
        email: "kate@example.com",
    },
    {
        id: "16",
        appointmentNo: "D016",
        appointmentType: "ENT",
        doctorName: "Dr. K. Ratnayake",
        date: "2025-06-07",
        hospitalLocation: "Maharagama",
        status: "accepted",
        address: "9 Temple Road, Maharagama",
        phone: "+94776789012",
        email: "kate@example.com",
    },
    {
        id: "17",
        appointmentNo: "D017",
        appointmentType: "Neurology",
        doctorName: "Dr. L. De Silva",
        date: "2025-06-11",
        hospitalLocation: "Colombo",
        status: "pending",
        address: "42 Flower Road, Colombo",
        phone: "+94771234567",
        email: "kate@example.com",
    },
    {
        id: "18",
        appointmentNo: "D018",
        appointmentType: "Ophthalmology",
        doctorName: "Dr. T. Mendis",
        date: "2025-06-15",
        hospitalLocation: "Kandy",
        status: "accepted",
        address: "8 Hill Street, Kandy",
        phone: "+94773456789",
        email: "kate@example.com",
    },
    {
        id: "19",
        appointmentNo: "D019",
        appointmentType: "Dermatology",
        doctorName: "Dr. P. Perera",
        date: "2025-06-19",
        hospitalLocation: "Galle",
        status: "cancelled",
        address: "3 Fort Lane, Galle",
        phone: "+94774567890",
        email: "kate@example.com",
    },
    {
        id: "20",
        appointmentNo: "D020",
        appointmentType: "General",
        doctorName: "Dr. R. Silva",
        date: "2025-06-23",
        hospitalLocation: "Colombo",
        status: "pending",
        address: "12 Lake View, Nugegoda",
        phone: "+94772345678",
        email: "kate@example.com",
    },
];
