/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DownloadUrlResponseDto,
  S3VaultControllerUploadFileBody
} from '../../interfaces';

import s3VaultControllerUploadFileMutator from '../../../config/api-config/axios';
import s3VaultControllerGetDownloadUrlMutator from '../../../config/api-config/axios';




/**
 * @summary Upload, hash, encrypt, and store a medical record file
 */
export const s3VaultControllerUploadFile = (
    s3VaultControllerUploadFileBody: S3VaultControllerUploadFileBody,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, s3VaultControllerUploadFileBody.file);
formData.append(`patientId`, s3VaultControllerUploadFileBody.patientId);
if(s3VaultControllerUploadFileBody.category !== undefined) {
 formData.append(`category`, s3VaultControllerUploadFileBody.category);
 }
if(s3VaultControllerUploadFileBody.notes !== undefined) {
 formData.append(`notes`, s3VaultControllerUploadFileBody.notes);
 }
if(s3VaultControllerUploadFileBody.doctorName !== undefined) {
 formData.append(`doctorName`, s3VaultControllerUploadFileBody.doctorName);
 }
if(s3VaultControllerUploadFileBody.hospitalName !== undefined) {
 formData.append(`hospitalName`, s3VaultControllerUploadFileBody.hospitalName);
 }
if(s3VaultControllerUploadFileBody.recordDate !== undefined) {
 formData.append(`recordDate`, s3VaultControllerUploadFileBody.recordDate);
 }

      return s3VaultControllerUploadFileMutator<void>(
      {url: `/api/s3-vault/upload`, method: 'POST',
       data: formData, signal
    },
      );
    }
  


export const getS3VaultControllerUploadFileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof s3VaultControllerUploadFile>>, TError,{data: S3VaultControllerUploadFileBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof s3VaultControllerUploadFile>>, TError,{data: S3VaultControllerUploadFileBody}, TContext> => {

const mutationKey = ['s3VaultControllerUploadFile'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof s3VaultControllerUploadFile>>, {data: S3VaultControllerUploadFileBody}> = (props) => {
          const {data} = props ?? {};

          return  s3VaultControllerUploadFile(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type S3VaultControllerUploadFileMutationResult = NonNullable<Awaited<ReturnType<typeof s3VaultControllerUploadFile>>>
    export type S3VaultControllerUploadFileMutationBody = S3VaultControllerUploadFileBody
    export type S3VaultControllerUploadFileMutationError = unknown

    /**
 * @summary Upload, hash, encrypt, and store a medical record file
 */
export const useS3VaultControllerUploadFile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof s3VaultControllerUploadFile>>, TError,{data: S3VaultControllerUploadFileBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof s3VaultControllerUploadFile>>,
        TError,
        {data: S3VaultControllerUploadFileBody},
        TContext
      > => {
      return useMutation(getS3VaultControllerUploadFileMutationOptions(options), queryClient);
    }
    /**
 * @summary Generate a presigned S3 URL for record download
 */
export const s3VaultControllerGetDownloadUrl = (
    recordId: string,
 signal?: AbortSignal
) => {
      
      
      return s3VaultControllerGetDownloadUrlMutator<DownloadUrlResponseDto>(
      {url: `/api/s3-vault/download/${recordId}`, method: 'GET', signal
    },
      );
    }
  



export const getS3VaultControllerGetDownloadUrlQueryKey = (recordId: string,) => {
    return [
    `/api/s3-vault/download/${recordId}`
    ] as const;
    }

    
export const getS3VaultControllerGetDownloadUrlQueryOptions = <TData = Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>, TError = unknown>(recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getS3VaultControllerGetDownloadUrlQueryKey(recordId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>> = ({ signal }) => s3VaultControllerGetDownloadUrl(recordId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(recordId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type S3VaultControllerGetDownloadUrlQueryResult = NonNullable<Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>>
export type S3VaultControllerGetDownloadUrlQueryError = unknown


export function useS3VaultControllerGetDownloadUrl<TData = Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>, TError = unknown>(
 recordId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>,
          TError,
          Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useS3VaultControllerGetDownloadUrl<TData = Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>, TError = unknown>(
 recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>,
          TError,
          Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useS3VaultControllerGetDownloadUrl<TData = Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>, TError = unknown>(
 recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Generate a presigned S3 URL for record download
 */

export function useS3VaultControllerGetDownloadUrl<TData = Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>, TError = unknown>(
 recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof s3VaultControllerGetDownloadUrl>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getS3VaultControllerGetDownloadUrlQueryOptions(recordId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




