import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1775252452217 implements MigrationInterface {
    name = 'Init1775252452217'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "auth_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "clerkUserId" character varying NOT NULL, "email" character varying NOT NULL, "firstName" character varying(100), "lastName" character varying(100), "isDemoDisabled" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_935cd86a07c11d84ef1c8bee8f1" UNIQUE ("clerkUserId"), CONSTRAINT "UQ_13d8b49e55a8b06bee6bbc828fb" UNIQUE ("email"), CONSTRAINT "PK_c88cc8077366b470dafc2917366" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "medical_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "dob" date, "biological_sex" character varying(20), "gender_identity" character varying(50), "blood_type" character varying(10), "height_cm" numeric(5,2), "weight_kg" numeric(5,2), "organ_donor" boolean NOT NULL DEFAULT false, "insurance_provider" character varying, "insurance_policy_no" character varying, "insurance_group_no" character varying, "insurance_card_front" character varying, "insurance_card_back" character varying, "primary_physician_name" character varying, "primary_physician_contact" character varying, "smoking_status" character varying, "alcohol_consumption" character varying, "exercise_level" character varying, "dietary_preferences" character varying, "person_id" uuid, CONSTRAINT "REL_88faa9691ec6ccc483fa08c2bc" UNIQUE ("person_id"), CONSTRAINT "PK_14c460cfc3e52e6e6fb5c03a54d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "allergies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "allergen_name" character varying NOT NULL, "category" character varying, "severity" character varying, "reaction" text, "person_id" uuid, CONSTRAINT "PK_f72e0cf363a832b8fa8cf657118" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "medications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "dosage" character varying, "frequency" character varying, "purpose" character varying, "is_active" boolean NOT NULL DEFAULT true, "person_id" uuid, CONSTRAINT "PK_cdee49fe7cd79db13340150d356" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "emergency_contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "relationship" character varying, "phone_number" character varying NOT NULL, "is_primary" boolean NOT NULL DEFAULT false, "person_id" uuid, CONSTRAINT "PK_8be191845b6fca1c4e5ba5bd7d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "persons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "email" character varying NOT NULL, "phone" character varying(100), "addressLine1" character varying(100), "addressLine2" character varying(100), "city" character varying(100), "zipCode" character varying(100), "gender" character varying(100), "dob" character varying(100), "authUserId" uuid, CONSTRAINT "UQ_928155276ca8852f3c440cc2b2c" UNIQUE ("email"), CONSTRAINT "UQ_e07de5476a091b328b3b86cc847" UNIQUE ("authUserId"), CONSTRAINT "REL_e07de5476a091b328b3b86cc84" UNIQUE ("authUserId"), CONSTRAINT "PK_74278d8812a049233ce41440ac7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "global_patients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "did" character varying NOT NULL, "primary_doc_type" character varying, "doc_identifier_hash" character varying, "public_key" text, "enc_profile_blob" text, "is_verified" boolean NOT NULL DEFAULT false, "person_id" uuid, CONSTRAINT "UQ_59bfba8727c74ae24b023da8124" UNIQUE ("did"), CONSTRAINT "REL_f1588ada264c6b95949ea8b031" UNIQUE ("person_id"), CONSTRAINT "PK_b52fcbfa76e1bc08eb648310090" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."institutions_status_enum" AS ENUM('ACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "institutions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "license_number" character varying NOT NULL, "status" "public"."institutions_status_enum" NOT NULL DEFAULT 'ACTIVE', "contact_details" json, CONSTRAINT "UQ_6d914281c403f50f4bc490c0caa" UNIQUE ("license_number"), CONSTRAINT "PK_0be7539dcdba335470dc05e9690" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "event_type" character varying NOT NULL, "actor_did" character varying NOT NULL, "patient_id" character varying, "target_resource" character varying, "ip_address" character varying, "timestamp" TIMESTAMP NOT NULL, "additional_data" json, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_queue_type_enum" AS ENUM('PUSH', 'EMAIL', 'SMS')`);
        await queryRunner.query(`CREATE TABLE "notification_queue" ("id" BIGSERIAL NOT NULL, "target_did" character varying NOT NULL, "message" character varying NOT NULL, "type" "public"."notification_queue_type_enum" NOT NULL, "is_sent" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "sent_at" TIMESTAMP, CONSTRAINT "PK_60a6aa02d8322bf9912101f47d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."guardian_links_relationship_enum" AS ENUM('FATHER', 'MOTHER', 'GUARDIAN')`);
        await queryRunner.query(`CREATE TABLE "guardian_links" ("id" BIGSERIAL NOT NULL, "minor_did" character varying NOT NULL, "guardian_did" character varying NOT NULL, "relationship" "public"."guardian_links_relationship_enum" NOT NULL, "doc_reference" character varying, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a5ef0b9de24a0d6e502b752df40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "record_registry" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "patient_did" character varying NOT NULL, "institution_id" uuid, "record_hash" character varying NOT NULL, "vault_id" character varying, "metadata" json, "is_revoked" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_aafcef6fd251a4657e53480f905" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."access_requests_status_enum" AS ENUM('PENDING', 'GRANTED', 'REJECTED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "access_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "requester_inst_id" uuid NOT NULL, "requester_staff_id" character varying, "patient_did" character varying NOT NULL, "record_registry_id" uuid, "status" "public"."access_requests_status_enum" NOT NULL DEFAULT 'PENDING', "rejection_reason" text, "requested_at" TIMESTAMP NOT NULL, "granted_at" TIMESTAMP, "expiry_at" TIMESTAMP, CONSTRAINT "PK_f89e51c15e3dbea13aa248fe128" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."medical_records_category_enum" AS ENUM('lab_report', 'prescription', 'imaging', 'discharge_summary', 'vaccination', 'other')`);
        await queryRunner.query(`CREATE TABLE "medical_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "patientId" uuid NOT NULL, "uploaderId" uuid NOT NULL, "s3Uri" text, "documentHash" text, "encryptedAesKey" text, "original_file_name" text, "mime_type" character varying(100), "file_name" character varying, "file_url" character varying, "file_type" character varying, "file_size" bigint, "category" "public"."medical_records_category_enum" NOT NULL DEFAULT 'other', "notes" text, "doctor_name" character varying(200), "hospital_name" character varying(200), "record_date" date, "person_id" uuid, CONSTRAINT "PK_c200c0b76638124b7ed51424823" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."consent_requests_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "consent_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "requester_id" uuid NOT NULL, "patient_id" uuid NOT NULL, "record_id" uuid NOT NULL, "status" "public"."consent_requests_status_enum" NOT NULL DEFAULT 'PENDING', "expires_at" TIMESTAMP, CONSTRAINT "PK_6e56fb576d9de99095cc4a8ba65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."appointments_status_enum" AS ENUM('pending', 'accepted', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "appointments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "date" TIMESTAMP NOT NULL, "doctor" character varying(100) NOT NULL, "type" character varying(100) NOT NULL, "location" character varying(100) NOT NULL, "address" character varying(200), "phone" character varying(50), "email" character varying(100), "status" "public"."appointments_status_enum" NOT NULL DEFAULT 'pending', "patientId" uuid NOT NULL, CONSTRAINT "PK_4a437a9a27e948726b8bb3e36ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "medical_profiles" ADD CONSTRAINT "FK_88faa9691ec6ccc483fa08c2bcf" FOREIGN KEY ("person_id") REFERENCES "persons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "allergies" ADD CONSTRAINT "FK_44fd99f13b49b312f98f5de0a14" FOREIGN KEY ("person_id") REFERENCES "persons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medications" ADD CONSTRAINT "FK_c3c6efea78837f1be20bfe2dede" FOREIGN KEY ("person_id") REFERENCES "persons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emergency_contacts" ADD CONSTRAINT "FK_8804e7fd55a5f68091ce0dfd8b0" FOREIGN KEY ("person_id") REFERENCES "persons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "persons" ADD CONSTRAINT "FK_e07de5476a091b328b3b86cc847" FOREIGN KEY ("authUserId") REFERENCES "auth_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "global_patients" ADD CONSTRAINT "FK_f1588ada264c6b95949ea8b0318" FOREIGN KEY ("person_id") REFERENCES "persons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_queue" ADD CONSTRAINT "FK_880948d3ddc430e2295a16af4f4" FOREIGN KEY ("target_did") REFERENCES "global_patients"("did") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guardian_links" ADD CONSTRAINT "FK_1d509f01dc81b05afe415ff7ccd" FOREIGN KEY ("minor_did") REFERENCES "global_patients"("did") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guardian_links" ADD CONSTRAINT "FK_cc05f5ee485e0bfdeb54ad68551" FOREIGN KEY ("guardian_did") REFERENCES "global_patients"("did") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "record_registry" ADD CONSTRAINT "FK_668239e465f8641ef471809ada7" FOREIGN KEY ("patient_did") REFERENCES "global_patients"("did") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "record_registry" ADD CONSTRAINT "FK_ae405fcd34eb0638e71a457d69d" FOREIGN KEY ("institution_id") REFERENCES "institutions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "access_requests" ADD CONSTRAINT "FK_9d26ef2430f42a938e98e67a7ed" FOREIGN KEY ("requester_inst_id") REFERENCES "institutions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "access_requests" ADD CONSTRAINT "FK_d1d629eeb65582f358626ef4966" FOREIGN KEY ("patient_did") REFERENCES "global_patients"("did") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "access_requests" ADD CONSTRAINT "FK_7a458cefaaa9060d4ba4e2c2825" FOREIGN KEY ("record_registry_id") REFERENCES "record_registry"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_records" ADD CONSTRAINT "FK_d1792275ff345f83dd3760becdb" FOREIGN KEY ("person_id") REFERENCES "persons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consent_requests" ADD CONSTRAINT "FK_490fca94f8560858aae172f8d2f" FOREIGN KEY ("requester_id") REFERENCES "auth_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consent_requests" ADD CONSTRAINT "FK_d67c5e43670ff460aa6cafc4ed5" FOREIGN KEY ("patient_id") REFERENCES "auth_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consent_requests" ADD CONSTRAINT "FK_afe2d4f2495e225421c31abf279" FOREIGN KEY ("record_id") REFERENCES "medical_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d" FOREIGN KEY ("patientId") REFERENCES "persons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d"`);
        await queryRunner.query(`ALTER TABLE "consent_requests" DROP CONSTRAINT "FK_afe2d4f2495e225421c31abf279"`);
        await queryRunner.query(`ALTER TABLE "consent_requests" DROP CONSTRAINT "FK_d67c5e43670ff460aa6cafc4ed5"`);
        await queryRunner.query(`ALTER TABLE "consent_requests" DROP CONSTRAINT "FK_490fca94f8560858aae172f8d2f"`);
        await queryRunner.query(`ALTER TABLE "medical_records" DROP CONSTRAINT "FK_d1792275ff345f83dd3760becdb"`);
        await queryRunner.query(`ALTER TABLE "access_requests" DROP CONSTRAINT "FK_7a458cefaaa9060d4ba4e2c2825"`);
        await queryRunner.query(`ALTER TABLE "access_requests" DROP CONSTRAINT "FK_d1d629eeb65582f358626ef4966"`);
        await queryRunner.query(`ALTER TABLE "access_requests" DROP CONSTRAINT "FK_9d26ef2430f42a938e98e67a7ed"`);
        await queryRunner.query(`ALTER TABLE "record_registry" DROP CONSTRAINT "FK_ae405fcd34eb0638e71a457d69d"`);
        await queryRunner.query(`ALTER TABLE "record_registry" DROP CONSTRAINT "FK_668239e465f8641ef471809ada7"`);
        await queryRunner.query(`ALTER TABLE "guardian_links" DROP CONSTRAINT "FK_cc05f5ee485e0bfdeb54ad68551"`);
        await queryRunner.query(`ALTER TABLE "guardian_links" DROP CONSTRAINT "FK_1d509f01dc81b05afe415ff7ccd"`);
        await queryRunner.query(`ALTER TABLE "notification_queue" DROP CONSTRAINT "FK_880948d3ddc430e2295a16af4f4"`);
        await queryRunner.query(`ALTER TABLE "global_patients" DROP CONSTRAINT "FK_f1588ada264c6b95949ea8b0318"`);
        await queryRunner.query(`ALTER TABLE "persons" DROP CONSTRAINT "FK_e07de5476a091b328b3b86cc847"`);
        await queryRunner.query(`ALTER TABLE "emergency_contacts" DROP CONSTRAINT "FK_8804e7fd55a5f68091ce0dfd8b0"`);
        await queryRunner.query(`ALTER TABLE "medications" DROP CONSTRAINT "FK_c3c6efea78837f1be20bfe2dede"`);
        await queryRunner.query(`ALTER TABLE "allergies" DROP CONSTRAINT "FK_44fd99f13b49b312f98f5de0a14"`);
        await queryRunner.query(`ALTER TABLE "medical_profiles" DROP CONSTRAINT "FK_88faa9691ec6ccc483fa08c2bcf"`);
        await queryRunner.query(`DROP TABLE "appointments"`);
        await queryRunner.query(`DROP TYPE "public"."appointments_status_enum"`);
        await queryRunner.query(`DROP TABLE "consent_requests"`);
        await queryRunner.query(`DROP TYPE "public"."consent_requests_status_enum"`);
        await queryRunner.query(`DROP TABLE "medical_records"`);
        await queryRunner.query(`DROP TYPE "public"."medical_records_category_enum"`);
        await queryRunner.query(`DROP TABLE "access_requests"`);
        await queryRunner.query(`DROP TYPE "public"."access_requests_status_enum"`);
        await queryRunner.query(`DROP TABLE "record_registry"`);
        await queryRunner.query(`DROP TABLE "guardian_links"`);
        await queryRunner.query(`DROP TYPE "public"."guardian_links_relationship_enum"`);
        await queryRunner.query(`DROP TABLE "notification_queue"`);
        await queryRunner.query(`DROP TYPE "public"."notification_queue_type_enum"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "institutions"`);
        await queryRunner.query(`DROP TYPE "public"."institutions_status_enum"`);
        await queryRunner.query(`DROP TABLE "global_patients"`);
        await queryRunner.query(`DROP TABLE "persons"`);
        await queryRunner.query(`DROP TABLE "emergency_contacts"`);
        await queryRunner.query(`DROP TABLE "medications"`);
        await queryRunner.query(`DROP TABLE "allergies"`);
        await queryRunner.query(`DROP TABLE "medical_profiles"`);
        await queryRunner.query(`DROP TABLE "auth_users"`);
    }

}
