/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import profileControllerGetMyProfileMutator from '../../../config/api-config/axios';
import profileControllerGetProfileMutator from '../../../config/api-config/axios';
import profileControllerGetProfileByEmailMutator from '../../../config/api-config/axios';
import profileControllerGetProfileByAuthUserIdMutator from '../../../config/api-config/axios';
import profileControllerUpdatePersonMutator from '../../../config/api-config/axios';
import profileControllerUpdateMedicalProfileMutator from '../../../config/api-config/axios';
import profileControllerAddAllergyMutator from '../../../config/api-config/axios';
import profileControllerDeleteAllergyMutator from '../../../config/api-config/axios';
import profileControllerAddMedicationMutator from '../../../config/api-config/axios';
import profileControllerDeleteMedicationMutator from '../../../config/api-config/axios';
import profileControllerAddEmergencyContactMutator from '../../../config/api-config/axios';
import profileControllerDeleteEmergencyContactMutator from '../../../config/api-config/axios';




/**
 * @summary Get profile for the logged-in user (via JWT cookie)
 */
export const profileControllerGetMyProfile = (
    
 signal?: AbortSignal
) => {
      
      
      return profileControllerGetMyProfileMutator<void>(
      {url: `/api/profile/me`, method: 'GET', signal
    },
      );
    }
  



export const getProfileControllerGetMyProfileQueryKey = () => {
    return [
    `/api/profile/me`
    ] as const;
    }

    
export const getProfileControllerGetMyProfileQueryOptions = <TData = Awaited<ReturnType<typeof profileControllerGetMyProfile>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetMyProfile>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProfileControllerGetMyProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerGetMyProfile>>> = ({ signal }) => profileControllerGetMyProfile(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetMyProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProfileControllerGetMyProfileQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerGetMyProfile>>>
export type ProfileControllerGetMyProfileQueryError = unknown


export function useProfileControllerGetMyProfile<TData = Awaited<ReturnType<typeof profileControllerGetMyProfile>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetMyProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerGetMyProfile>>,
          TError,
          Awaited<ReturnType<typeof profileControllerGetMyProfile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProfileControllerGetMyProfile<TData = Awaited<ReturnType<typeof profileControllerGetMyProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetMyProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerGetMyProfile>>,
          TError,
          Awaited<ReturnType<typeof profileControllerGetMyProfile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProfileControllerGetMyProfile<TData = Awaited<ReturnType<typeof profileControllerGetMyProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetMyProfile>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get profile for the logged-in user (via JWT cookie)
 */

export function useProfileControllerGetMyProfile<TData = Awaited<ReturnType<typeof profileControllerGetMyProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetMyProfile>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProfileControllerGetMyProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get full user profile by person ID
 */
export const profileControllerGetProfile = (
    personId: string,
 signal?: AbortSignal
) => {
      
      
      return profileControllerGetProfileMutator<void>(
      {url: `/api/profile/${personId}`, method: 'GET', signal
    },
      );
    }
  



export const getProfileControllerGetProfileQueryKey = (personId: string,) => {
    return [
    `/api/profile/${personId}`
    ] as const;
    }

    
export const getProfileControllerGetProfileQueryOptions = <TData = Awaited<ReturnType<typeof profileControllerGetProfile>>, TError = unknown>(personId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfile>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProfileControllerGetProfileQueryKey(personId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerGetProfile>>> = ({ signal }) => profileControllerGetProfile(personId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(personId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProfileControllerGetProfileQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerGetProfile>>>
export type ProfileControllerGetProfileQueryError = unknown


export function useProfileControllerGetProfile<TData = Awaited<ReturnType<typeof profileControllerGetProfile>>, TError = unknown>(
 personId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof profileControllerGetProfile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProfileControllerGetProfile<TData = Awaited<ReturnType<typeof profileControllerGetProfile>>, TError = unknown>(
 personId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof profileControllerGetProfile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProfileControllerGetProfile<TData = Awaited<ReturnType<typeof profileControllerGetProfile>>, TError = unknown>(
 personId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfile>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get full user profile by person ID
 */

export function useProfileControllerGetProfile<TData = Awaited<ReturnType<typeof profileControllerGetProfile>>, TError = unknown>(
 personId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfile>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProfileControllerGetProfileQueryOptions(personId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get full user profile by email
 */
export const profileControllerGetProfileByEmail = (
    email: string,
 signal?: AbortSignal
) => {
      
      
      return profileControllerGetProfileByEmailMutator<void>(
      {url: `/api/profile/email/${email}`, method: 'GET', signal
    },
      );
    }
  



export const getProfileControllerGetProfileByEmailQueryKey = (email: string,) => {
    return [
    `/api/profile/email/${email}`
    ] as const;
    }

    
export const getProfileControllerGetProfileByEmailQueryOptions = <TData = Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>, TError = unknown>(email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProfileControllerGetProfileByEmailQueryKey(email);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>> = ({ signal }) => profileControllerGetProfileByEmail(email, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(email), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProfileControllerGetProfileByEmailQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>>
export type ProfileControllerGetProfileByEmailQueryError = unknown


export function useProfileControllerGetProfileByEmail<TData = Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>, TError = unknown>(
 email: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>,
          TError,
          Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProfileControllerGetProfileByEmail<TData = Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>, TError = unknown>(
 email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>,
          TError,
          Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProfileControllerGetProfileByEmail<TData = Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>, TError = unknown>(
 email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get full user profile by email
 */

export function useProfileControllerGetProfileByEmail<TData = Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>, TError = unknown>(
 email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfileByEmail>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProfileControllerGetProfileByEmailQueryOptions(email,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get full user profile by Clerk user ID
 */
export const profileControllerGetProfileByAuthUserId = (
    clerkUserId: string,
 signal?: AbortSignal
) => {
      
      
      return profileControllerGetProfileByAuthUserIdMutator<void>(
      {url: `/api/profile/auth/${clerkUserId}`, method: 'GET', signal
    },
      );
    }
  



export const getProfileControllerGetProfileByAuthUserIdQueryKey = (clerkUserId: string,) => {
    return [
    `/api/profile/auth/${clerkUserId}`
    ] as const;
    }

    
export const getProfileControllerGetProfileByAuthUserIdQueryOptions = <TData = Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>, TError = unknown>(clerkUserId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProfileControllerGetProfileByAuthUserIdQueryKey(clerkUserId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>> = ({ signal }) => profileControllerGetProfileByAuthUserId(clerkUserId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(clerkUserId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProfileControllerGetProfileByAuthUserIdQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>>
export type ProfileControllerGetProfileByAuthUserIdQueryError = unknown


export function useProfileControllerGetProfileByAuthUserId<TData = Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>, TError = unknown>(
 clerkUserId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>,
          TError,
          Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProfileControllerGetProfileByAuthUserId<TData = Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>, TError = unknown>(
 clerkUserId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>,
          TError,
          Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProfileControllerGetProfileByAuthUserId<TData = Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>, TError = unknown>(
 clerkUserId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get full user profile by Clerk user ID
 */

export function useProfileControllerGetProfileByAuthUserId<TData = Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>, TError = unknown>(
 clerkUserId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerGetProfileByAuthUserId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProfileControllerGetProfileByAuthUserIdQueryOptions(clerkUserId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update personal details
 */
export const profileControllerUpdatePerson = (
    personId: string,
 signal?: AbortSignal
) => {
      
      
      return profileControllerUpdatePersonMutator<void>(
      {url: `/api/profile/${personId}/personal`, method: 'PATCH', signal
    },
      );
    }
  


export const getProfileControllerUpdatePersonMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerUpdatePerson>>, TError,{personId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof profileControllerUpdatePerson>>, TError,{personId: string}, TContext> => {

const mutationKey = ['profileControllerUpdatePerson'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof profileControllerUpdatePerson>>, {personId: string}> = (props) => {
          const {personId} = props ?? {};

          return  profileControllerUpdatePerson(personId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProfileControllerUpdatePersonMutationResult = NonNullable<Awaited<ReturnType<typeof profileControllerUpdatePerson>>>
    
    export type ProfileControllerUpdatePersonMutationError = unknown

    /**
 * @summary Update personal details
 */
export const useProfileControllerUpdatePerson = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerUpdatePerson>>, TError,{personId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof profileControllerUpdatePerson>>,
        TError,
        {personId: string},
        TContext
      > => {
      return useMutation(getProfileControllerUpdatePersonMutationOptions(options), queryClient);
    }
    /**
 * @summary Update medical profile
 */
export const profileControllerUpdateMedicalProfile = (
    personId: string,
 signal?: AbortSignal
) => {
      
      
      return profileControllerUpdateMedicalProfileMutator<void>(
      {url: `/api/profile/${personId}/medical`, method: 'PATCH', signal
    },
      );
    }
  


export const getProfileControllerUpdateMedicalProfileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerUpdateMedicalProfile>>, TError,{personId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof profileControllerUpdateMedicalProfile>>, TError,{personId: string}, TContext> => {

const mutationKey = ['profileControllerUpdateMedicalProfile'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof profileControllerUpdateMedicalProfile>>, {personId: string}> = (props) => {
          const {personId} = props ?? {};

          return  profileControllerUpdateMedicalProfile(personId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProfileControllerUpdateMedicalProfileMutationResult = NonNullable<Awaited<ReturnType<typeof profileControllerUpdateMedicalProfile>>>
    
    export type ProfileControllerUpdateMedicalProfileMutationError = unknown

    /**
 * @summary Update medical profile
 */
export const useProfileControllerUpdateMedicalProfile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerUpdateMedicalProfile>>, TError,{personId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof profileControllerUpdateMedicalProfile>>,
        TError,
        {personId: string},
        TContext
      > => {
      return useMutation(getProfileControllerUpdateMedicalProfileMutationOptions(options), queryClient);
    }
    /**
 * @summary Add allergy
 */
export const profileControllerAddAllergy = (
    personId: string,
 signal?: AbortSignal
) => {
      
      
      return profileControllerAddAllergyMutator<void>(
      {url: `/api/profile/${personId}/allergies`, method: 'POST', signal
    },
      );
    }
  


export const getProfileControllerAddAllergyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerAddAllergy>>, TError,{personId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof profileControllerAddAllergy>>, TError,{personId: string}, TContext> => {

const mutationKey = ['profileControllerAddAllergy'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof profileControllerAddAllergy>>, {personId: string}> = (props) => {
          const {personId} = props ?? {};

          return  profileControllerAddAllergy(personId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProfileControllerAddAllergyMutationResult = NonNullable<Awaited<ReturnType<typeof profileControllerAddAllergy>>>
    
    export type ProfileControllerAddAllergyMutationError = unknown

    /**
 * @summary Add allergy
 */
export const useProfileControllerAddAllergy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerAddAllergy>>, TError,{personId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof profileControllerAddAllergy>>,
        TError,
        {personId: string},
        TContext
      > => {
      return useMutation(getProfileControllerAddAllergyMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete allergy
 */
export const profileControllerDeleteAllergy = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return profileControllerDeleteAllergyMutator<void>(
      {url: `/api/profile/allergies/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getProfileControllerDeleteAllergyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerDeleteAllergy>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof profileControllerDeleteAllergy>>, TError,{id: string}, TContext> => {

const mutationKey = ['profileControllerDeleteAllergy'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof profileControllerDeleteAllergy>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  profileControllerDeleteAllergy(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProfileControllerDeleteAllergyMutationResult = NonNullable<Awaited<ReturnType<typeof profileControllerDeleteAllergy>>>
    
    export type ProfileControllerDeleteAllergyMutationError = unknown

    /**
 * @summary Delete allergy
 */
export const useProfileControllerDeleteAllergy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerDeleteAllergy>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof profileControllerDeleteAllergy>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getProfileControllerDeleteAllergyMutationOptions(options), queryClient);
    }
    /**
 * @summary Add medication
 */
export const profileControllerAddMedication = (
    personId: string,
 signal?: AbortSignal
) => {
      
      
      return profileControllerAddMedicationMutator<void>(
      {url: `/api/profile/${personId}/medications`, method: 'POST', signal
    },
      );
    }
  


export const getProfileControllerAddMedicationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerAddMedication>>, TError,{personId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof profileControllerAddMedication>>, TError,{personId: string}, TContext> => {

const mutationKey = ['profileControllerAddMedication'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof profileControllerAddMedication>>, {personId: string}> = (props) => {
          const {personId} = props ?? {};

          return  profileControllerAddMedication(personId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProfileControllerAddMedicationMutationResult = NonNullable<Awaited<ReturnType<typeof profileControllerAddMedication>>>
    
    export type ProfileControllerAddMedicationMutationError = unknown

    /**
 * @summary Add medication
 */
export const useProfileControllerAddMedication = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerAddMedication>>, TError,{personId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof profileControllerAddMedication>>,
        TError,
        {personId: string},
        TContext
      > => {
      return useMutation(getProfileControllerAddMedicationMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete medication
 */
export const profileControllerDeleteMedication = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return profileControllerDeleteMedicationMutator<void>(
      {url: `/api/profile/medications/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getProfileControllerDeleteMedicationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerDeleteMedication>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof profileControllerDeleteMedication>>, TError,{id: string}, TContext> => {

const mutationKey = ['profileControllerDeleteMedication'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof profileControllerDeleteMedication>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  profileControllerDeleteMedication(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProfileControllerDeleteMedicationMutationResult = NonNullable<Awaited<ReturnType<typeof profileControllerDeleteMedication>>>
    
    export type ProfileControllerDeleteMedicationMutationError = unknown

    /**
 * @summary Delete medication
 */
export const useProfileControllerDeleteMedication = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerDeleteMedication>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof profileControllerDeleteMedication>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getProfileControllerDeleteMedicationMutationOptions(options), queryClient);
    }
    /**
 * @summary Add emergency contact
 */
export const profileControllerAddEmergencyContact = (
    personId: string,
 signal?: AbortSignal
) => {
      
      
      return profileControllerAddEmergencyContactMutator<void>(
      {url: `/api/profile/${personId}/contacts`, method: 'POST', signal
    },
      );
    }
  


export const getProfileControllerAddEmergencyContactMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerAddEmergencyContact>>, TError,{personId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof profileControllerAddEmergencyContact>>, TError,{personId: string}, TContext> => {

const mutationKey = ['profileControllerAddEmergencyContact'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof profileControllerAddEmergencyContact>>, {personId: string}> = (props) => {
          const {personId} = props ?? {};

          return  profileControllerAddEmergencyContact(personId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProfileControllerAddEmergencyContactMutationResult = NonNullable<Awaited<ReturnType<typeof profileControllerAddEmergencyContact>>>
    
    export type ProfileControllerAddEmergencyContactMutationError = unknown

    /**
 * @summary Add emergency contact
 */
export const useProfileControllerAddEmergencyContact = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerAddEmergencyContact>>, TError,{personId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof profileControllerAddEmergencyContact>>,
        TError,
        {personId: string},
        TContext
      > => {
      return useMutation(getProfileControllerAddEmergencyContactMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete emergency contact
 */
export const profileControllerDeleteEmergencyContact = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return profileControllerDeleteEmergencyContactMutator<void>(
      {url: `/api/profile/contacts/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getProfileControllerDeleteEmergencyContactMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerDeleteEmergencyContact>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof profileControllerDeleteEmergencyContact>>, TError,{id: string}, TContext> => {

const mutationKey = ['profileControllerDeleteEmergencyContact'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof profileControllerDeleteEmergencyContact>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  profileControllerDeleteEmergencyContact(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProfileControllerDeleteEmergencyContactMutationResult = NonNullable<Awaited<ReturnType<typeof profileControllerDeleteEmergencyContact>>>
    
    export type ProfileControllerDeleteEmergencyContactMutationError = unknown

    /**
 * @summary Delete emergency contact
 */
export const useProfileControllerDeleteEmergencyContact = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileControllerDeleteEmergencyContact>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof profileControllerDeleteEmergencyContact>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getProfileControllerDeleteEmergencyContactMutationOptions(options), queryClient);
    }
    