# Use Node LTS
FROM node:20

# Set working directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy only package.json first (for caching)
COPY package.json ./

# Install dependencies
RUN pnpm install

# Copy rest of the app
COPY . .

# Build NestJS app
RUN pnpm build

# Expose port
EXPOSE 4001

# Start app
CMD ["node", "dist/main.js"]