
services:
  gateway:
    build: .
    container_name: trustmed-gateway
    ports:
      - "4001:4001"
    volumes:
      - /home/ubuntu/TrustMed/blockchain/fabric-samples/fabric-samples/test-network:/fabric
    environment:
      - FABRIC_PATH=/fabric
    restart: always