/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AcceptConsentDto
} from '../../interfaces';

import consentRequestsControllerRequestAccessMutator from '../../../config/api-config/axios';
import consentRequestsControllerGetStatusAndDownloadMutator from '../../../config/api-config/axios';
import consentRequestsControllerGetReceivedRequestsMutator from '../../../config/api-config/axios';
import consentRequestsControllerGetSentRequestsMutator from '../../../config/api-config/axios';
import consentRequestsControllerAcceptRequestMutator from '../../../config/api-config/axios';
import consentRequestsControllerRejectRequestMutator from '../../../config/api-config/axios';




/**
 * @summary Request access to a specific medical record
 */
export const consentRequestsControllerRequestAccess = (
    recordId: string,
 signal?: AbortSignal
) => {
      
      
      return consentRequestsControllerRequestAccessMutator<void>(
      {url: `/api/consent-requests/${recordId}`, method: 'POST', signal
    },
      );
    }
  


export const getConsentRequestsControllerRequestAccessMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof consentRequestsControllerRequestAccess>>, TError,{recordId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof consentRequestsControllerRequestAccess>>, TError,{recordId: string}, TContext> => {

const mutationKey = ['consentRequestsControllerRequestAccess'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof consentRequestsControllerRequestAccess>>, {recordId: string}> = (props) => {
          const {recordId} = props ?? {};

          return  consentRequestsControllerRequestAccess(recordId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ConsentRequestsControllerRequestAccessMutationResult = NonNullable<Awaited<ReturnType<typeof consentRequestsControllerRequestAccess>>>
    
    export type ConsentRequestsControllerRequestAccessMutationError = unknown

    /**
 * @summary Request access to a specific medical record
 */
export const useConsentRequestsControllerRequestAccess = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof consentRequestsControllerRequestAccess>>, TError,{recordId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof consentRequestsControllerRequestAccess>>,
        TError,
        {recordId: string},
        TContext
      > => {
      return useMutation(getConsentRequestsControllerRequestAccessMutationOptions(options), queryClient);
    }
    /**
 * @summary Check request status and get download URL if accepted
 */
export const consentRequestsControllerGetStatusAndDownload = (
    recordId: string,
 signal?: AbortSignal
) => {
      
      
      return consentRequestsControllerGetStatusAndDownloadMutator<void>(
      {url: `/api/consent-requests/${recordId}`, method: 'GET', signal
    },
      );
    }
  



export const getConsentRequestsControllerGetStatusAndDownloadQueryKey = (recordId: string,) => {
    return [
    `/api/consent-requests/${recordId}`
    ] as const;
    }

    
export const getConsentRequestsControllerGetStatusAndDownloadQueryOptions = <TData = Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>, TError = unknown>(recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConsentRequestsControllerGetStatusAndDownloadQueryKey(recordId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>> = ({ signal }) => consentRequestsControllerGetStatusAndDownload(recordId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(recordId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConsentRequestsControllerGetStatusAndDownloadQueryResult = NonNullable<Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>>
export type ConsentRequestsControllerGetStatusAndDownloadQueryError = unknown


export function useConsentRequestsControllerGetStatusAndDownload<TData = Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>, TError = unknown>(
 recordId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>,
          TError,
          Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConsentRequestsControllerGetStatusAndDownload<TData = Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>, TError = unknown>(
 recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>,
          TError,
          Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConsentRequestsControllerGetStatusAndDownload<TData = Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>, TError = unknown>(
 recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Check request status and get download URL if accepted
 */

export function useConsentRequestsControllerGetStatusAndDownload<TData = Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>, TError = unknown>(
 recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetStatusAndDownload>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConsentRequestsControllerGetStatusAndDownloadQueryOptions(recordId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get consent requests received by the patient
 */
export const consentRequestsControllerGetReceivedRequests = (
    
 signal?: AbortSignal
) => {
      
      
      return consentRequestsControllerGetReceivedRequestsMutator<void>(
      {url: `/api/consent-requests/me/received`, method: 'GET', signal
    },
      );
    }
  



export const getConsentRequestsControllerGetReceivedRequestsQueryKey = () => {
    return [
    `/api/consent-requests/me/received`
    ] as const;
    }

    
export const getConsentRequestsControllerGetReceivedRequestsQueryOptions = <TData = Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConsentRequestsControllerGetReceivedRequestsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>> = ({ signal }) => consentRequestsControllerGetReceivedRequests(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConsentRequestsControllerGetReceivedRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>>
export type ConsentRequestsControllerGetReceivedRequestsQueryError = unknown


export function useConsentRequestsControllerGetReceivedRequests<TData = Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>,
          TError,
          Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConsentRequestsControllerGetReceivedRequests<TData = Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>,
          TError,
          Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConsentRequestsControllerGetReceivedRequests<TData = Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get consent requests received by the patient
 */

export function useConsentRequestsControllerGetReceivedRequests<TData = Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetReceivedRequests>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConsentRequestsControllerGetReceivedRequestsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get consent requests sent by the requester (doctor/hospital)
 */
export const consentRequestsControllerGetSentRequests = (
    
 signal?: AbortSignal
) => {
      
      
      return consentRequestsControllerGetSentRequestsMutator<void>(
      {url: `/api/consent-requests/me/sent`, method: 'GET', signal
    },
      );
    }
  



export const getConsentRequestsControllerGetSentRequestsQueryKey = () => {
    return [
    `/api/consent-requests/me/sent`
    ] as const;
    }

    
export const getConsentRequestsControllerGetSentRequestsQueryOptions = <TData = Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConsentRequestsControllerGetSentRequestsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>> = ({ signal }) => consentRequestsControllerGetSentRequests(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConsentRequestsControllerGetSentRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>>
export type ConsentRequestsControllerGetSentRequestsQueryError = unknown


export function useConsentRequestsControllerGetSentRequests<TData = Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>,
          TError,
          Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConsentRequestsControllerGetSentRequests<TData = Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>,
          TError,
          Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConsentRequestsControllerGetSentRequests<TData = Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get consent requests sent by the requester (doctor/hospital)
 */

export function useConsentRequestsControllerGetSentRequests<TData = Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consentRequestsControllerGetSentRequests>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConsentRequestsControllerGetSentRequestsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Accept a consent request with a specific duration
 */
export const consentRequestsControllerAcceptRequest = (
    id: string,
    acceptConsentDto: AcceptConsentDto,
 signal?: AbortSignal
) => {
      
      
      return consentRequestsControllerAcceptRequestMutator<void>(
      {url: `/api/consent-requests/${id}/accept`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: acceptConsentDto, signal
    },
      );
    }
  


export const getConsentRequestsControllerAcceptRequestMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof consentRequestsControllerAcceptRequest>>, TError,{id: string;data: AcceptConsentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof consentRequestsControllerAcceptRequest>>, TError,{id: string;data: AcceptConsentDto}, TContext> => {

const mutationKey = ['consentRequestsControllerAcceptRequest'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof consentRequestsControllerAcceptRequest>>, {id: string;data: AcceptConsentDto}> = (props) => {
          const {id,data} = props ?? {};

          return  consentRequestsControllerAcceptRequest(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ConsentRequestsControllerAcceptRequestMutationResult = NonNullable<Awaited<ReturnType<typeof consentRequestsControllerAcceptRequest>>>
    export type ConsentRequestsControllerAcceptRequestMutationBody = AcceptConsentDto
    export type ConsentRequestsControllerAcceptRequestMutationError = unknown

    /**
 * @summary Accept a consent request with a specific duration
 */
export const useConsentRequestsControllerAcceptRequest = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof consentRequestsControllerAcceptRequest>>, TError,{id: string;data: AcceptConsentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof consentRequestsControllerAcceptRequest>>,
        TError,
        {id: string;data: AcceptConsentDto},
        TContext
      > => {
      return useMutation(getConsentRequestsControllerAcceptRequestMutationOptions(options), queryClient);
    }
    /**
 * @summary Reject a consent request
 */
export const consentRequestsControllerRejectRequest = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return consentRequestsControllerRejectRequestMutator<void>(
      {url: `/api/consent-requests/${id}/reject`, method: 'PATCH', signal
    },
      );
    }
  


export const getConsentRequestsControllerRejectRequestMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof consentRequestsControllerRejectRequest>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof consentRequestsControllerRejectRequest>>, TError,{id: string}, TContext> => {

const mutationKey = ['consentRequestsControllerRejectRequest'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof consentRequestsControllerRejectRequest>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  consentRequestsControllerRejectRequest(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ConsentRequestsControllerRejectRequestMutationResult = NonNullable<Awaited<ReturnType<typeof consentRequestsControllerRejectRequest>>>
    
    export type ConsentRequestsControllerRejectRequestMutationError = unknown

    /**
 * @summary Reject a consent request
 */
export const useConsentRequestsControllerRejectRequest = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof consentRequestsControllerRejectRequest>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof consentRequestsControllerRejectRequest>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getConsentRequestsControllerRejectRequestMutationOptions(options), queryClient);
    }
    