/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import type { BlockchainHealthResponseDtoStatus } from './blockchainHealthResponseDtoStatus';
import type { NetworkStatusDto } from './networkStatusDto';
import type { SubStatusDto } from './subStatusDto';

export interface BlockchainHealthResponseDto {
  status: BlockchainHealthResponseDtoStatus;
  gateway: SubStatusDto;
  network: NetworkStatusDto;
}
