/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */

export interface CreateMedicalRecordResponseDto {
  id: string;
  personId: string;
  fileName: string;
  fileUrl: string;
  fileType: string;
  fileSize: number;
  category: string;
  notes?: string;
  doctorName?: string;
  hospitalName?: string;
  recordDate?: string;
  createdAt: string;
  updatedAt: string;
}
