/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import type { DatabaseHealthStatus } from './databaseHealthStatus';

export interface DatabaseHealth {
  status: DatabaseHealthStatus;
  /** The type of database currently in use */
  type: string;
}
