/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */

export type NetworkStatusDtoStatus = typeof NetworkStatusDtoStatus[keyof typeof NetworkStatusDtoStatus];


export const NetworkStatusDtoStatus = {
  UP: 'UP',
  DOWN: 'DOWN',
  DEGRADED: 'DEGRADED',
} as const;
