/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateMedicalRecordRequestDto,
  CreateMedicalRecordResponseDto,
  DeleteMedicalRecordResponseDto,
  MedicalRecordItemResponseDto,
  MedicalRecordListResponseDto,
  UpdateMedicalRecordRequestDto
} from '../../interfaces';

import medicalRecordControllerDownloadMutator from '../../../config/api-config/axios';
import medicalRecordControllerUpdateMutator from '../../../config/api-config/axios';
import medicalRecordControllerGetByIdMutator from '../../../config/api-config/axios';
import medicalRecordControllerDeleteByIdMutator from '../../../config/api-config/axios';
import medicalRecordControllerCreateMutator from '../../../config/api-config/axios';
import medicalRecordControllerGetAllByAuthUserIdMutator from '../../../config/api-config/axios';




/**
 * @summary Download a decrypted medical record
 */
export const medicalRecordControllerDownload = (
    recordId: string,
 signal?: AbortSignal
) => {
      
      
      return medicalRecordControllerDownloadMutator<void>(
      {url: `/api/medical-records/${recordId}/download`, method: 'GET', signal
    },
      );
    }
  



export const getMedicalRecordControllerDownloadQueryKey = (recordId: string,) => {
    return [
    `/api/medical-records/${recordId}/download`
    ] as const;
    }

    
export const getMedicalRecordControllerDownloadQueryOptions = <TData = Awaited<ReturnType<typeof medicalRecordControllerDownload>>, TError = unknown>(recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerDownload>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMedicalRecordControllerDownloadQueryKey(recordId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof medicalRecordControllerDownload>>> = ({ signal }) => medicalRecordControllerDownload(recordId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(recordId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerDownload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MedicalRecordControllerDownloadQueryResult = NonNullable<Awaited<ReturnType<typeof medicalRecordControllerDownload>>>
export type MedicalRecordControllerDownloadQueryError = unknown


export function useMedicalRecordControllerDownload<TData = Awaited<ReturnType<typeof medicalRecordControllerDownload>>, TError = unknown>(
 recordId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerDownload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof medicalRecordControllerDownload>>,
          TError,
          Awaited<ReturnType<typeof medicalRecordControllerDownload>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMedicalRecordControllerDownload<TData = Awaited<ReturnType<typeof medicalRecordControllerDownload>>, TError = unknown>(
 recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerDownload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof medicalRecordControllerDownload>>,
          TError,
          Awaited<ReturnType<typeof medicalRecordControllerDownload>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMedicalRecordControllerDownload<TData = Awaited<ReturnType<typeof medicalRecordControllerDownload>>, TError = unknown>(
 recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerDownload>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download a decrypted medical record
 */

export function useMedicalRecordControllerDownload<TData = Awaited<ReturnType<typeof medicalRecordControllerDownload>>, TError = unknown>(
 recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerDownload>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMedicalRecordControllerDownloadQueryOptions(recordId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const medicalRecordControllerUpdate = (
    authuserId: string,
    recordId: string,
    updateMedicalRecordRequestDto: UpdateMedicalRecordRequestDto,
 signal?: AbortSignal
) => {
      
      
      return medicalRecordControllerUpdateMutator<MedicalRecordItemResponseDto>(
      {url: `/api/medical-records/${authuserId}/${recordId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateMedicalRecordRequestDto, signal
    },
      );
    }
  


export const getMedicalRecordControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof medicalRecordControllerUpdate>>, TError,{authuserId: string;recordId: string;data: UpdateMedicalRecordRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof medicalRecordControllerUpdate>>, TError,{authuserId: string;recordId: string;data: UpdateMedicalRecordRequestDto}, TContext> => {

const mutationKey = ['medicalRecordControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof medicalRecordControllerUpdate>>, {authuserId: string;recordId: string;data: UpdateMedicalRecordRequestDto}> = (props) => {
          const {authuserId,recordId,data} = props ?? {};

          return  medicalRecordControllerUpdate(authuserId,recordId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type MedicalRecordControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof medicalRecordControllerUpdate>>>
    export type MedicalRecordControllerUpdateMutationBody = UpdateMedicalRecordRequestDto
    export type MedicalRecordControllerUpdateMutationError = unknown

    export const useMedicalRecordControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof medicalRecordControllerUpdate>>, TError,{authuserId: string;recordId: string;data: UpdateMedicalRecordRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof medicalRecordControllerUpdate>>,
        TError,
        {authuserId: string;recordId: string;data: UpdateMedicalRecordRequestDto},
        TContext
      > => {
      return useMutation(getMedicalRecordControllerUpdateMutationOptions(options), queryClient);
    }
    export const medicalRecordControllerGetById = (
    authuserId: string,
    recordId: string,
 signal?: AbortSignal
) => {
      
      
      return medicalRecordControllerGetByIdMutator<MedicalRecordItemResponseDto>(
      {url: `/api/medical-records/${authuserId}/${recordId}`, method: 'GET', signal
    },
      );
    }
  



export const getMedicalRecordControllerGetByIdQueryKey = (authuserId: string,
    recordId: string,) => {
    return [
    `/api/medical-records/${authuserId}/${recordId}`
    ] as const;
    }

    
export const getMedicalRecordControllerGetByIdQueryOptions = <TData = Awaited<ReturnType<typeof medicalRecordControllerGetById>>, TError = unknown>(authuserId: string,
    recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerGetById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMedicalRecordControllerGetByIdQueryKey(authuserId,recordId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof medicalRecordControllerGetById>>> = ({ signal }) => medicalRecordControllerGetById(authuserId,recordId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(authuserId && recordId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerGetById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MedicalRecordControllerGetByIdQueryResult = NonNullable<Awaited<ReturnType<typeof medicalRecordControllerGetById>>>
export type MedicalRecordControllerGetByIdQueryError = unknown


export function useMedicalRecordControllerGetById<TData = Awaited<ReturnType<typeof medicalRecordControllerGetById>>, TError = unknown>(
 authuserId: string,
    recordId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerGetById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof medicalRecordControllerGetById>>,
          TError,
          Awaited<ReturnType<typeof medicalRecordControllerGetById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMedicalRecordControllerGetById<TData = Awaited<ReturnType<typeof medicalRecordControllerGetById>>, TError = unknown>(
 authuserId: string,
    recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerGetById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof medicalRecordControllerGetById>>,
          TError,
          Awaited<ReturnType<typeof medicalRecordControllerGetById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMedicalRecordControllerGetById<TData = Awaited<ReturnType<typeof medicalRecordControllerGetById>>, TError = unknown>(
 authuserId: string,
    recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerGetById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMedicalRecordControllerGetById<TData = Awaited<ReturnType<typeof medicalRecordControllerGetById>>, TError = unknown>(
 authuserId: string,
    recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerGetById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMedicalRecordControllerGetByIdQueryOptions(authuserId,recordId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const medicalRecordControllerDeleteById = (
    authuserId: string,
    recordId: string,
 signal?: AbortSignal
) => {
      
      
      return medicalRecordControllerDeleteByIdMutator<DeleteMedicalRecordResponseDto>(
      {url: `/api/medical-records/${authuserId}/${recordId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getMedicalRecordControllerDeleteByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof medicalRecordControllerDeleteById>>, TError,{authuserId: string;recordId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof medicalRecordControllerDeleteById>>, TError,{authuserId: string;recordId: string}, TContext> => {

const mutationKey = ['medicalRecordControllerDeleteById'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof medicalRecordControllerDeleteById>>, {authuserId: string;recordId: string}> = (props) => {
          const {authuserId,recordId} = props ?? {};

          return  medicalRecordControllerDeleteById(authuserId,recordId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type MedicalRecordControllerDeleteByIdMutationResult = NonNullable<Awaited<ReturnType<typeof medicalRecordControllerDeleteById>>>
    
    export type MedicalRecordControllerDeleteByIdMutationError = unknown

    export const useMedicalRecordControllerDeleteById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof medicalRecordControllerDeleteById>>, TError,{authuserId: string;recordId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof medicalRecordControllerDeleteById>>,
        TError,
        {authuserId: string;recordId: string},
        TContext
      > => {
      return useMutation(getMedicalRecordControllerDeleteByIdMutationOptions(options), queryClient);
    }
    export const medicalRecordControllerCreate = (
    createMedicalRecordRequestDto: CreateMedicalRecordRequestDto,
 signal?: AbortSignal
) => {
      
      
      return medicalRecordControllerCreateMutator<CreateMedicalRecordResponseDto>(
      {url: `/api/medical-records`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMedicalRecordRequestDto, signal
    },
      );
    }
  


export const getMedicalRecordControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof medicalRecordControllerCreate>>, TError,{data: CreateMedicalRecordRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof medicalRecordControllerCreate>>, TError,{data: CreateMedicalRecordRequestDto}, TContext> => {

const mutationKey = ['medicalRecordControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof medicalRecordControllerCreate>>, {data: CreateMedicalRecordRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  medicalRecordControllerCreate(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type MedicalRecordControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof medicalRecordControllerCreate>>>
    export type MedicalRecordControllerCreateMutationBody = CreateMedicalRecordRequestDto
    export type MedicalRecordControllerCreateMutationError = unknown

    export const useMedicalRecordControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof medicalRecordControllerCreate>>, TError,{data: CreateMedicalRecordRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof medicalRecordControllerCreate>>,
        TError,
        {data: CreateMedicalRecordRequestDto},
        TContext
      > => {
      return useMutation(getMedicalRecordControllerCreateMutationOptions(options), queryClient);
    }
    export const medicalRecordControllerGetAllByAuthUserId = (
    authuserId: string,
 signal?: AbortSignal
) => {
      
      
      return medicalRecordControllerGetAllByAuthUserIdMutator<MedicalRecordListResponseDto>(
      {url: `/api/medical-records/${authuserId}`, method: 'GET', signal
    },
      );
    }
  



export const getMedicalRecordControllerGetAllByAuthUserIdQueryKey = (authuserId: string,) => {
    return [
    `/api/medical-records/${authuserId}`
    ] as const;
    }

    
export const getMedicalRecordControllerGetAllByAuthUserIdQueryOptions = <TData = Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>, TError = unknown>(authuserId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMedicalRecordControllerGetAllByAuthUserIdQueryKey(authuserId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>> = ({ signal }) => medicalRecordControllerGetAllByAuthUserId(authuserId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(authuserId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MedicalRecordControllerGetAllByAuthUserIdQueryResult = NonNullable<Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>>
export type MedicalRecordControllerGetAllByAuthUserIdQueryError = unknown


export function useMedicalRecordControllerGetAllByAuthUserId<TData = Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>, TError = unknown>(
 authuserId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>,
          TError,
          Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMedicalRecordControllerGetAllByAuthUserId<TData = Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>, TError = unknown>(
 authuserId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>,
          TError,
          Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMedicalRecordControllerGetAllByAuthUserId<TData = Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>, TError = unknown>(
 authuserId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMedicalRecordControllerGetAllByAuthUserId<TData = Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>, TError = unknown>(
 authuserId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof medicalRecordControllerGetAllByAuthUserId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMedicalRecordControllerGetAllByAuthUserIdQueryOptions(authuserId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




