/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import aiChatControllerChatMutator from '../../../config/api-config/axios';




export const aiChatControllerChat = (
    
 signal?: AbortSignal
) => {
      
      
      return aiChatControllerChatMutator<void>(
      {url: `/api/ai-chat`, method: 'POST', signal
    },
      );
    }
  


export const getAiChatControllerChatMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof aiChatControllerChat>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof aiChatControllerChat>>, TError,void, TContext> => {

const mutationKey = ['aiChatControllerChat'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof aiChatControllerChat>>, void> = () => {
          

          return  aiChatControllerChat()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AiChatControllerChatMutationResult = NonNullable<Awaited<ReturnType<typeof aiChatControllerChat>>>
    
    export type AiChatControllerChatMutationError = unknown

    export const useAiChatControllerChat = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof aiChatControllerChat>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof aiChatControllerChat>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAiChatControllerChatMutationOptions(options), queryClient);
    }
    