/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppointmentResponseDto,
  AppointmentsControllerFindAllByAuthUserId200,
  AppointmentsControllerFindAllByAuthUserIdParams,
  AppointmentsControllerFindOneByIdParams,
  CreateAppointmentDto,
  DeleteAppointmentDto,
  EditAppointmentDto
} from '../../interfaces';

import appointmentsControllerCreateMutator from '../../../config/api-config/axios';
import appointmentsControllerFindAllByAuthUserIdMutator from '../../../config/api-config/axios';
import appointmentsControllerEditMutator from '../../../config/api-config/axios';
import appointmentsControllerDeleteMutator from '../../../config/api-config/axios';
import appointmentsControllerFindOneByIdMutator from '../../../config/api-config/axios';




/**
 * @summary Create a new appointment
 */
export const appointmentsControllerCreate = (
    createAppointmentDto: CreateAppointmentDto,
 signal?: AbortSignal
) => {
      
      
      return appointmentsControllerCreateMutator<AppointmentResponseDto>(
      {url: `/api/appointments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAppointmentDto, signal
    },
      );
    }
  


export const getAppointmentsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appointmentsControllerCreate>>, TError,{data: CreateAppointmentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof appointmentsControllerCreate>>, TError,{data: CreateAppointmentDto}, TContext> => {

const mutationKey = ['appointmentsControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof appointmentsControllerCreate>>, {data: CreateAppointmentDto}> = (props) => {
          const {data} = props ?? {};

          return  appointmentsControllerCreate(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AppointmentsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof appointmentsControllerCreate>>>
    export type AppointmentsControllerCreateMutationBody = CreateAppointmentDto
    export type AppointmentsControllerCreateMutationError = unknown

    /**
 * @summary Create a new appointment
 */
export const useAppointmentsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appointmentsControllerCreate>>, TError,{data: CreateAppointmentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof appointmentsControllerCreate>>,
        TError,
        {data: CreateAppointmentDto},
        TContext
      > => {
      return useMutation(getAppointmentsControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary List all appointments for a person by auth user id
 */
export const appointmentsControllerFindAllByAuthUserId = (
    params: AppointmentsControllerFindAllByAuthUserIdParams,
 signal?: AbortSignal
) => {
      
      
      return appointmentsControllerFindAllByAuthUserIdMutator<AppointmentsControllerFindAllByAuthUserId200>(
      {url: `/api/appointments`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getAppointmentsControllerFindAllByAuthUserIdQueryKey = (params?: AppointmentsControllerFindAllByAuthUserIdParams,) => {
    return [
    `/api/appointments`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAppointmentsControllerFindAllByAuthUserIdQueryOptions = <TData = Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>, TError = unknown>(params: AppointmentsControllerFindAllByAuthUserIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppointmentsControllerFindAllByAuthUserIdQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>> = ({ signal }) => appointmentsControllerFindAllByAuthUserId(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppointmentsControllerFindAllByAuthUserIdQueryResult = NonNullable<Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>>
export type AppointmentsControllerFindAllByAuthUserIdQueryError = unknown


export function useAppointmentsControllerFindAllByAuthUserId<TData = Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>, TError = unknown>(
 params: AppointmentsControllerFindAllByAuthUserIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>,
          TError,
          Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppointmentsControllerFindAllByAuthUserId<TData = Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>, TError = unknown>(
 params: AppointmentsControllerFindAllByAuthUserIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>,
          TError,
          Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppointmentsControllerFindAllByAuthUserId<TData = Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>, TError = unknown>(
 params: AppointmentsControllerFindAllByAuthUserIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all appointments for a person by auth user id
 */

export function useAppointmentsControllerFindAllByAuthUserId<TData = Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>, TError = unknown>(
 params: AppointmentsControllerFindAllByAuthUserIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appointmentsControllerFindAllByAuthUserId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppointmentsControllerFindAllByAuthUserIdQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Edit appointment by id
 */
export const appointmentsControllerEdit = (
    editAppointmentDto: EditAppointmentDto,
 signal?: AbortSignal
) => {
      
      
      return appointmentsControllerEditMutator<AppointmentResponseDto>(
      {url: `/api/appointments`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: editAppointmentDto, signal
    },
      );
    }
  


export const getAppointmentsControllerEditMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appointmentsControllerEdit>>, TError,{data: EditAppointmentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof appointmentsControllerEdit>>, TError,{data: EditAppointmentDto}, TContext> => {

const mutationKey = ['appointmentsControllerEdit'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof appointmentsControllerEdit>>, {data: EditAppointmentDto}> = (props) => {
          const {data} = props ?? {};

          return  appointmentsControllerEdit(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AppointmentsControllerEditMutationResult = NonNullable<Awaited<ReturnType<typeof appointmentsControllerEdit>>>
    export type AppointmentsControllerEditMutationBody = EditAppointmentDto
    export type AppointmentsControllerEditMutationError = unknown

    /**
 * @summary Edit appointment by id
 */
export const useAppointmentsControllerEdit = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appointmentsControllerEdit>>, TError,{data: EditAppointmentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof appointmentsControllerEdit>>,
        TError,
        {data: EditAppointmentDto},
        TContext
      > => {
      return useMutation(getAppointmentsControllerEditMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete appointment by id
 */
export const appointmentsControllerDelete = (
    deleteAppointmentDto: DeleteAppointmentDto,
 signal?: AbortSignal
) => {
      
      
      return appointmentsControllerDeleteMutator<unknown>(
      {url: `/api/appointments`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteAppointmentDto, signal
    },
      );
    }
  


export const getAppointmentsControllerDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appointmentsControllerDelete>>, TError,{data: DeleteAppointmentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof appointmentsControllerDelete>>, TError,{data: DeleteAppointmentDto}, TContext> => {

const mutationKey = ['appointmentsControllerDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof appointmentsControllerDelete>>, {data: DeleteAppointmentDto}> = (props) => {
          const {data} = props ?? {};

          return  appointmentsControllerDelete(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AppointmentsControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof appointmentsControllerDelete>>>
    export type AppointmentsControllerDeleteMutationBody = DeleteAppointmentDto
    export type AppointmentsControllerDeleteMutationError = unknown

    /**
 * @summary Delete appointment by id
 */
export const useAppointmentsControllerDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appointmentsControllerDelete>>, TError,{data: DeleteAppointmentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof appointmentsControllerDelete>>,
        TError,
        {data: DeleteAppointmentDto},
        TContext
      > => {
      return useMutation(getAppointmentsControllerDeleteMutationOptions(options), queryClient);
    }
    /**
 * @summary Find appointment by id
 */
export const appointmentsControllerFindOneById = (
    params: AppointmentsControllerFindOneByIdParams,
 signal?: AbortSignal
) => {
      
      
      return appointmentsControllerFindOneByIdMutator<AppointmentResponseDto>(
      {url: `/api/appointments/find`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getAppointmentsControllerFindOneByIdQueryKey = (params?: AppointmentsControllerFindOneByIdParams,) => {
    return [
    `/api/appointments/find`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAppointmentsControllerFindOneByIdQueryOptions = <TData = Awaited<ReturnType<typeof appointmentsControllerFindOneById>>, TError = unknown>(params: AppointmentsControllerFindOneByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appointmentsControllerFindOneById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppointmentsControllerFindOneByIdQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof appointmentsControllerFindOneById>>> = ({ signal }) => appointmentsControllerFindOneById(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appointmentsControllerFindOneById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppointmentsControllerFindOneByIdQueryResult = NonNullable<Awaited<ReturnType<typeof appointmentsControllerFindOneById>>>
export type AppointmentsControllerFindOneByIdQueryError = unknown


export function useAppointmentsControllerFindOneById<TData = Awaited<ReturnType<typeof appointmentsControllerFindOneById>>, TError = unknown>(
 params: AppointmentsControllerFindOneByIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appointmentsControllerFindOneById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appointmentsControllerFindOneById>>,
          TError,
          Awaited<ReturnType<typeof appointmentsControllerFindOneById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppointmentsControllerFindOneById<TData = Awaited<ReturnType<typeof appointmentsControllerFindOneById>>, TError = unknown>(
 params: AppointmentsControllerFindOneByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appointmentsControllerFindOneById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appointmentsControllerFindOneById>>,
          TError,
          Awaited<ReturnType<typeof appointmentsControllerFindOneById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppointmentsControllerFindOneById<TData = Awaited<ReturnType<typeof appointmentsControllerFindOneById>>, TError = unknown>(
 params: AppointmentsControllerFindOneByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appointmentsControllerFindOneById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Find appointment by id
 */

export function useAppointmentsControllerFindOneById<TData = Awaited<ReturnType<typeof appointmentsControllerFindOneById>>, TError = unknown>(
 params: AppointmentsControllerFindOneByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appointmentsControllerFindOneById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppointmentsControllerFindOneByIdQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




