/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TrustMed Core API
 * API documentation for the TrustMed Core backend
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetHistoryParams,
  MedicalHistoryResponseDto
} from '../../interfaces';

import getHistoryMutator from '../../../config/api-config/axios';




/**
 * @summary Get audit-log & blockchain history for the authenticated patient
 */
export const getHistory = (
    params?: GetHistoryParams,
 signal?: AbortSignal
) => {
      
      
      return getHistoryMutator<MedicalHistoryResponseDto>(
      {url: `/api/medical-history`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetHistoryQueryKey = (params?: GetHistoryParams,) => {
    return [
    `/api/medical-history`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(params?: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHistory>>> = ({ signal }) => getHistory(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getHistory>>>
export type GetHistoryQueryError = unknown


export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params: undefined |  GetHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistory>>,
          TError,
          Awaited<ReturnType<typeof getHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params?: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHistory>>,
          TError,
          Awaited<ReturnType<typeof getHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params?: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get audit-log & blockchain history for the authenticated patient
 */

export function useGetHistory<TData = Awaited<ReturnType<typeof getHistory>>, TError = unknown>(
 params?: GetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHistory>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




