name: Trigger auto deployment for core-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ devops-azure ]
    paths:
    - '**'
    - '.github/workflows/core-backend-AutoDeployTrigger-385e22d3-dcd8-45b6-bd3e-56b95af04265.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.COREBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COREBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COREBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}apps/core-backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.COREBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COREBACKEND_REGISTRY_PASSWORD }}
          containerAppName: core-backend
          resourceGroup: trustmed-health-dev
          imageToBuild: harithatk/core-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


