name: Deploy Dev Environment

on:
  push:
    branches:
      - feat/dev-env

jobs:
  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Pull Vercel Environment (core-frontend)
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          
      - name: Build Project Artifacts (core-frontend)
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          
      - name: Deploy Project Artifacts to Vercel (core-frontend)
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  deploy-backend:
    name: Deploy Backend to Oracle VM 1
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BACKEND_ORACLE_HOST }}
          username: ${{ secrets.BACKEND_ORACLE_USERNAME }}
          key: ${{ secrets.BACKEND_ORACLE_SSH_KEY }}
          script: |
            cd /var/www/trustmed
            git fetch origin feat/dev-env
            git checkout feat/dev-env
            git pull origin feat/dev-env
            docker compose -f docker-compose.dev-env.yml up -d --build core-backend

